### ISSUE TITLE
Visiting a profile should also trigger a profile (e.g., tag, photo, etc.) update

### ISSUE THREAD

**Issue by danbugs** [danbugs/smithereens#111]
**Describe the solution you'd like**
I thought I had done this already, but that doesn't seem to be the case. Visiting https://smithe.net/player/2191110 shows the "Captinricard" tag but this user has changed their tag to "bool went0_2 = true;". This is a pretty easy issue to fix because it just requires making a backend route to call update (https://github.com/danbugs/smithereens/blob/00529589b28c4e2273b22018de7393710f26b5e8/lib/src/player.rs#L122 ) when someone visits that player's profile.

**Additional context**
n/a

**Comment by danbugs** [comment]
@CERLgit ~ I am assigning you to this issue !

**Comment by ghost** [comment]
🫡
